#!/usr/bin/env python3
"""Backlog Batch 2:
   lead-generation, google-business-profile, website-redesign,
   connected-tv-advertising, apple-search-ads
"""
import os, json

BASE = os.path.join(os.path.dirname(os.path.abspath(__file__)), "services")
os.makedirs(BASE, exist_ok=True)

SERVICES = {

    "lead-generation": {
        "title_tag":  "Lead Generation Agency | B2B & B2C Lead Gen Services | Lumo AI",
        "meta_desc":  "Lead generation services from Lumo AI Agency. Multi-channel lead gen — SEO, paid ads, email outreach, and content — delivering qualified leads for US businesses. Free lead gen audit.",
        "canonical":  "https://lumoaiagency.com/services/lead-generation",
        "og_title":   "Lead Generation Agency | Lumo AI Agency",
        "og_desc":    "Consistent qualified leads without the guesswork. Lumo builds multi-channel lead generation systems — SEO, paid, outbound, and content — that fill your pipeline with prospects ready to buy.",
        "h1_html":    "Lead Generation Systems That <span class=\"hl-lime\">Fill Your Pipeline</span> Month After Month",
        "badge":      "Lead Generation Specialists",
        "lead":       "Most businesses have an inconsistent lead problem — feast-or-famine cycles driven by referrals and occasional campaigns. Lumo builds systematic lead generation programs across SEO, paid media, outbound, and content that deliver consistent qualified prospects every month, regardless of referral volume.",
        "stat1_num": "61%", "stat1_lbl": "Of marketers say lead generation is their top challenge",
        "stat2_num": "3x",  "stat2_lbl": "More leads generated by multi-channel vs. single-channel approach",
        "stat3_num": "80%", "stat3_lbl": "Of B2B leads never convert due to poor nurture follow-up",
        "why_h2": "Why Single-Channel Lead Generation Always Hits a Ceiling",
        "why_p1": "Businesses that rely on a single lead source — referrals, Google Ads, cold email — are one algorithm change, budget cut, or inbox filter away from a pipeline crisis. Diversified lead generation programs are more resilient and more scalable: when one channel slows, others compensate. When one channel succeeds, the audience data it generates improves targeting on every other channel.",
        "why_p2": "The conversion funnel problem compounds single-channel limitations. Even with abundant leads, most businesses convert only 2–5% of prospects because follow-up is inconsistent, nurture sequences don't exist, and sales teams chase every lead equally regardless of qualification. Lumo builds lead generation programs that include lead qualification scoring and automated nurture — ensuring your sales team spends time on leads that are actually ready to buy.",
        "why_p3": "Lumo's lead generation approach starts with your ideal customer profile — who has the problem you solve, the authority to buy, and the budget to do so. Every channel and campaign is calibrated to attract this specific profile, not generic traffic. We track leads from first touch to closed revenue, so you know exactly which channels are generating ROI, not just volume.",
        "services_h2": "Our Lead Generation Services",
        "services": [
            ("🔍", "SEO Lead Generation", "Organic lead capture through search — targeting high-intent keywords, optimising landing pages for conversion, building content that attracts qualified buyers at each stage of the research process."),
            ("💰", "Paid Lead Generation", "Google Ads, Meta, and LinkedIn lead generation campaigns — lead form ads, landing page campaigns, and retargeting sequences that capture and qualify prospects at each funnel stage."),
            ("📧", "Outbound Email Prospecting", "Targeted cold email outreach to ICP contacts — list building, personalised sequence writing, deliverability management, and A/B testing — generating pipeline from prospects who haven't found you yet."),
            ("📝", "Content-Driven Lead Gen", "Lead magnets, gated resources, webinars, and educational content that attract qualified prospects and exchange value for contact information — building list assets while generating immediate leads."),
            ("⚙️", "Lead Qualification & Scoring", "Lead scoring model implementation — behavioural and demographic scoring that identifies sales-ready leads automatically, routing qualified prospects to sales and cold contacts to nurture sequences."),
            ("📊", "Pipeline Attribution & Reporting", "End-to-end lead attribution — first touch, last touch, and multi-touch models connecting marketing channels to closed revenue — with monthly reporting on lead volume, quality, and conversion by source."),
        ],
        "process": [
            ("🎯", "ICP & Channel Strategy", "Define ideal customer profile, analyse where ICPs research and can be reached, select highest-ROI lead generation channels, and set lead volume and quality targets for each channel."),
            ("🏗️", "Build Lead Infrastructure", "Create landing pages, lead magnets, lead capture forms, CRM integration, lead scoring rules, and nurture sequences — the infrastructure that captures and qualifies leads before sales engagement."),
            ("🚀", "Launch & Generate", "Activate paid campaigns, outbound sequences, and content distribution simultaneously — monitoring lead volume, quality, and cost-per-lead across all channels in the first 30 days."),
            ("📈", "Optimise & Scale", "Monthly channel performance review, lead quality scoring calibration, budget reallocation to highest-ROI channels, and new channel testing as baseline performance data matures."),
        ],
        "price_from": "$2,500",
        "price_note": "per month — includes multi-channel strategy, campaign management, and pipeline reporting (ad spend separate)",
        "faqs": [
            ("What's the difference between lead generation and demand generation?", "Demand generation creates awareness and interest in your product among people who may not know they need it — it's top-of-funnel, brand-building activity. Lead generation captures contact information from people who are already aware of a problem and are evaluating solutions — it's mid-to-bottom-funnel, pipeline-building activity. Most effective programs combine both: demand gen builds the audience pool, lead gen harvests prospects from it."),
            ("How quickly can we expect leads to start coming in?", "Timeline depends on channels used. Paid lead generation (Google Ads, Meta lead forms) can generate leads within days of launch. Outbound email sequences typically generate first responses within 2–4 weeks. SEO-driven lead generation takes 3–6 months to ramp as content indexes and ranks. Lumo typically launches paid and outbound channels first for immediate pipeline, while SEO and content lead gen builds over time for lower long-term CPL."),
            ("What does a qualified lead look like, and how do you score them?", "Qualification criteria are defined with you in the strategy phase, based on your ICP and sales team's definition of a sales-ready lead. Typical B2B qualification factors: company size, industry, job title, and demonstrated buying intent (pages visited, content downloaded, form completions). We implement a point-based scoring model in your CRM or marketing automation platform that surfaces leads above your qualification threshold for sales outreach."),
            ("How do you ensure lead quality, not just volume?", "Volume metrics (number of leads) without quality metrics (lead-to-opportunity rate, close rate by channel) are vanity numbers. Lumo tracks lead quality by channel using a consistent qualification model — reporting not just how many leads each channel generated, but what percentage became opportunities and what percentage closed. This data drives budget allocation toward channels that generate profitable customers, not just high-cost leads."),
            ("Can lead generation work for both B2B and B2C businesses?", "Yes — the tactics differ significantly. B2B lead generation prioritises LinkedIn targeting, content marketing, and outbound prospecting to specific job titles. B2C lead generation emphasises paid social, SEO, and content-to-email list building at higher volume with lower individual lead value. Lumo tailors the channel mix and qualification model to your specific business model, average deal size, and sales cycle length."),
        ],
        "cta_h2": "Ready to Build a Lead Generation System That Works While You Sleep?",
        "cta_sub": "Get a free lead generation audit — we'll map your current lead sources, identify pipeline gaps, and show you exactly how much revenue you're leaving on the table without a systematic multi-channel approach.",
        "schema_service_name": "Lead Generation Services",
        "schema_service_desc": "Multi-channel lead generation for US businesses — SEO, paid ads, outbound email, content marketing, and lead qualification systems that fill pipelines consistently.",
    },

    "google-business-profile": {
        "title_tag":  "Google Business Profile Management | GBP Optimisation Agency | Lumo AI",
        "meta_desc":  "Google Business Profile management from Lumo AI Agency. GBP setup, optimisation, post scheduling, review management, and local pack ranking for US businesses. Free GBP audit.",
        "canonical":  "https://lumoaiagency.com/services/google-business-profile",
        "og_title":   "Google Business Profile Management | Lumo AI Agency",
        "og_desc":    "Your Google Business Profile is your most visible digital asset — 84% of customers find businesses through Google Search and Maps. Lumo optimises and manages GBP for US businesses to win local pack rankings.",
        "h1_html":    "Google Business Profile That <span class=\"hl-lime\">Wins the Local Pack</span> & Drives Calls",
        "badge":      "GBP Optimisation Specialists",
        "lead":       "84% of consumers use Google Search and Maps to find local businesses. Your Google Business Profile is visible before your website in most local searches — yet most profiles are incomplete, unoptimised, and unmanaged. Lumo's GBP management program maximises your local visibility and converts searchers into callers.",
        "stat1_num": "84%",  "stat1_lbl": "Of consumers use Google Search and Maps to find local businesses",
        "stat2_num": "56%",  "stat2_lbl": "Of businesses haven't claimed their GBP listing",
        "stat3_num": "2.7x", "stat3_lbl": "More likely to be considered reputable with a complete GBP",
        "why_h2": "Why Your Google Business Profile Is Your Most Important Local Asset",
        "why_p1": "When someone searches for your service locally, the Google local pack (the map with 3 business listings) appears above all organic results and often above paid ads. The businesses in the local pack capture the majority of local search clicks — and GBP optimisation is the primary factor determining who appears there. A complete, well-managed GBP profile with strong review signals outranks incomplete competitors regardless of website quality.",
        "why_p2": "Most businesses set up their GBP once and never touch it again. This is a significant competitive opportunity. Google actively rewards GBP profiles that are kept current — regular posts, photo uploads, updated business hours, answered questions, and active review responses all signal to Google that your business is active and engaged. Inactive profiles lose local pack position to competitors who are actively managing theirs.",
        "why_p3": "Lumo's GBP management program covers every signal that influences local pack ranking: profile completeness, category selection, business description optimisation, photo strategy, regular Google Post publishing, Q&A management, and review generation and response. We monitor your local pack position weekly and adjust our approach based on what's driving ranking movement in your specific market.",
        "services_h2": "Our Google Business Profile Services",
        "services": [
            ("✅", "GBP Setup & Verification", "New GBP creation and verification, existing profile claim and recovery, duplicate listing suppression, and initial profile completeness audit — the foundation before any optimisation begins."),
            ("⚙️", "Profile Optimisation", "Business name, category, and description optimisation — selecting the most accurate and highest-traffic categories, writing keyword-rich descriptions, adding all service areas, setting products and services, and configuring all available profile attributes."),
            ("📸", "Photo & Video Management", "Professional photo strategy — exterior, interior, team, product/service, and logo uploads — with regular refresh schedule. Video upload for higher engagement signals. Photo volume and quality directly correlate with local pack performance."),
            ("📝", "Google Posts & Updates", "Weekly Google Post publishing — offers, events, product announcements, and COVID-19 updates — keeping your profile active and providing keyword-rich content that supports local ranking signals."),
            ("⭐", "Review Generation & Response", "Systematic review request program triggering at post-service satisfaction peaks, professional response management for every review, and Q&A monitoring with accurate, keyword-containing answers."),
            ("📊", "GBP Analytics & Reporting", "Monthly GBP Insights reporting — search impressions, direction requests, call volume, website clicks, and photo views — with competitive local pack position tracking and ranking trend analysis."),
        ],
        "process": [
            ("🔍", "Audit & Claim", "GBP audit covering completeness score, category accuracy, photo volume, review health, and competitor comparison — followed by profile claim/verification and immediate completeness fixes."),
            ("⚙️", "Optimise & Build", "Full profile optimisation, photo upload programme, Google Post calendar, review generation system launch, and Q&A population — completing all optimisation within the first 30 days."),
            ("🔄", "Manage & Maintain", "Ongoing weekly Posts, review monitoring and response within 24 hours, photo refreshes, business information updates, and monthly GBP Insights reporting."),
            ("📈", "Track & Improve", "Weekly local pack position monitoring, competitor tracking, review velocity analysis, and quarterly strategy adjustments to improve ranking in your specific local market."),
        ],
        "price_from": "$400",
        "price_note": "per month — includes full profile management, post scheduling, review responses, and monthly reporting",
        "faqs": [
            ("What is the Google local pack and how do I get in it?", "The Google local pack is the map with 3 business listings that appears at the top of search results for local queries (e.g., 'dentist near me', 'plumber Austin TX'). Ranking factors include: GBP profile completeness and category accuracy, review quantity and quality (rating and recency), distance from the searcher's location, website authority and local relevance, and citation consistency across directories. GBP optimisation addresses all of these factors except location."),
            ("How long does it take to improve local pack ranking?", "Timeline varies by market competitiveness. In less competitive markets (smaller cities, niche services), GBP optimisation improvements can show ranking gains within 4–8 weeks. In highly competitive markets (major cities, popular service categories), improvement takes 3–6 months of sustained optimisation and review generation. Lumo sets realistic expectations based on your specific market's competitive landscape before starting."),
            ("What's the difference between GBP and local SEO?", "GBP management focuses specifically on your Google Business Profile — the listing that appears in Google Maps and the local pack. Local SEO is broader — it includes GBP, but also your website's local optimisation (location pages, local schema, NAP consistency), citation building across directories, and link acquisition from local sources. GBP management is the most impactful single local SEO action; Lumo offers both as standalone and combined services."),
            ("Can you manage GBP for multiple locations?", "Yes — Lumo manages GBP for multi-location businesses as a systemised program. Each location gets its own profile optimisation, dedicated photo uploads, location-specific Posts, review management, and reporting. We manage the programme centrally to ensure brand consistency while keeping each profile location-specific. Pricing scales per location."),
            ("What happens if someone posts a fake or malicious review?", "Google's policy prohibits fake, irrelevant, or conflict-of-interest reviews. If you receive a review that violates these policies, Lumo will flag it for Google review with documented rationale. Google does investigate and remove policy-violating reviews, but the process takes time (typically 1–4 weeks) and isn't guaranteed. While flagging proceeds, we draft and publish a professional, empathetic response that signals to future readers that your business takes all feedback seriously."),
        ],
        "cta_h2": "Ready to Win the Local Pack and Drive More Calls From Google?",
        "cta_sub": "Get a free GBP audit — we'll score your current profile completeness, review health, and local pack position, then show you exactly what it would take to rank above your competitors.",
        "schema_service_name": "Google Business Profile Management",
        "schema_service_desc": "Google Business Profile optimisation and management for US businesses — GBP setup, profile optimisation, post management, review generation, and local pack ranking.",
    },

    "website-redesign": {
        "title_tag":  "Website Redesign Agency | Conversion-Focused Redesigns | Lumo AI",
        "meta_desc":  "Website redesign services from Lumo AI Agency. Conversion-focused redesigns for WordPress, Shopify, and custom sites — with SEO equity preservation, performance optimisation, and brand consistency. Free audit.",
        "canonical":  "https://lumoaiagency.com/services/website-redesign",
        "og_title":   "Website Redesign Agency | Lumo AI Agency",
        "og_desc":    "A website redesign that loses your SEO equity isn't a redesign — it's a setback. Lumo builds redesigns that improve conversion rates, preserve organic rankings, and modernise your brand without starting over.",
        "h1_html":    "Website Redesign That <span class=\"hl-lime\">Improves Conversions</span> Without Losing Rankings",
        "badge":      "Website Redesign Specialists",
        "lead":       "Most website redesigns lose 20–60% of organic traffic in the first 90 days — through broken redirects, URL structure changes, and lost page authority. Lumo redesigns websites that convert better and rank better, with SEO preservation as a core project requirement from day one, not an afterthought.",
        "stat1_num": "75%",  "stat1_lbl": "Of users judge business credibility on website design",
        "stat2_num": "60%",  "stat2_lbl": "Of website redesigns cause measurable traffic drops without SEO planning",
        "stat3_num": "35%",  "stat3_lbl": "Average conversion rate improvement from strategic redesign",
        "why_h2": "Why Most Website Redesigns Hurt More Than They Help",
        "why_p1": "The typical redesign process starts with visual design and ends with a developer pushing the new site live — with no redirect mapping, no URL structure analysis, and no consideration of how Google has indexed the current site. The result is a beautiful new website that Google treats as a brand new domain, resetting years of accumulated authority and dropping rankings that took months or years to build.",
        "why_p2": "Conversion problems compound the SEO risk. Most redesigns are driven by the desire for a fresh look rather than a data-informed understanding of what's actually causing the current site to underperform. Without analysing which pages convert, where users drop off, and what the traffic patterns look like, redesigns frequently remove elements that were working and add elements that look impressive but don't drive conversions.",
        "why_p3": "Lumo's redesign process starts with your current data — traffic sources, conversion rates by page, user behaviour, and SEO equity analysis — before any design decisions are made. We map every existing URL to its new equivalent, implement 301 redirects correctly, preserve canonical signals, and verify Google's crawlability of the new site architecture before launch. Your new site looks better, converts better, and ranks better.",
        "services_h2": "Our Website Redesign Services",
        "services": [
            ("🔍", "Pre-Redesign SEO Audit", "Traffic analysis, URL inventory, backlink profile audit, ranking position snapshot, conversion rate baseline, and user behaviour review — establishing what must be preserved before any design or development decisions."),
            ("🎨", "Conversion-Focused Design", "Design strategy grounded in conversion principles — user journey mapping, information architecture redesign, wireframes for key pages, visual design aligned with brand standards, and responsive mobile-first execution."),
            ("🔄", "URL Mapping & Redirects", "Comprehensive redirect map for every existing URL — 1-to-1 where possible, best-match redirects for pages that change structure — implemented and tested before launch with redirect validation tooling."),
            ("⚡", "Performance Optimisation", "Core Web Vitals optimisation built into the rebuild — image compression, lazy loading, server-side caching, font loading optimisation, and script management for sub-2s mobile load times."),
            ("🔧", "SEO Technical Foundation", "Schema markup, canonical tags, XML sitemap, robots.txt, Open Graph meta, heading structure, and internal linking architecture — all configured correctly in the new site before launch."),
            ("✅", "Pre-Launch QA & Monitoring", "Pre-launch checklist: redirect verification, crawl simulation, conversion tracking test, cross-browser testing, GA4 and Search Console setup — plus 30-day post-launch monitoring for ranking and traffic anomalies."),
        ],
        "process": [
            ("🔍", "Discovery & Audit", "Current site traffic analysis, SEO equity audit, conversion funnel analysis, URL inventory, competitor benchmarking, and brand direction — producing a redesign brief that defines what must improve and what must be preserved."),
            ("🎨", "Design & Architecture", "Information architecture redesign, wireframes, visual design mockups, and SEO-informed URL structure planning — reviewed and approved before any development begins."),
            ("🏗️", "Build & Redirect", "New site development on staging environment, redirect map implementation, technical SEO configuration, performance optimisation, and full QA before production go-live."),
            ("🚀", "Launch & Monitor", "Controlled launch with redirect verification, immediate Search Console inspection of new URLs, post-launch crawl for errors, and 30-day traffic and ranking monitoring with rapid response for any anomalies."),
        ],
        "price_from": "$5,000",
        "price_note": "for a standard redesign — larger sites and custom functionality from $10,000+",
        "faqs": [
            ("How do you prevent losing rankings during a redesign?", "Ranking preservation requires four things: a complete URL inventory of every indexed page, a redirect map assigning a 301 redirect from every old URL to its closest equivalent on the new site, pre-launch redirect testing to verify correct implementation, and post-launch monitoring in Google Search Console to catch crawl errors, coverage issues, and ranking drops within 24 hours of going live. Lumo treats all four as non-negotiable components of every redesign."),
            ("Should we change our URL structure during a redesign?", "Changing URL structure creates redirect chains that dilute link equity and require careful mapping. If your current URL structure is logical and SEO-friendly, preserve it. If it's genuinely broken (no categorisation, session IDs, parameters), a redesign is the right time to fix it — with careful 301 redirects from old to new. Lumo provides a URL structure recommendation in the discovery phase based on your current equity distribution and the new site architecture."),
            ("How long does a website redesign take?", "A standard informational website redesign takes 8–12 weeks from discovery to launch. A complex e-commerce redesign or site with custom functionality takes 14–20 weeks. The timeline is driven by the number of page templates required, integration complexity, and client review rounds. SEO preservation work (URL audit, redirect mapping, technical configuration) adds approximately 2 weeks to the total timeline — but prevents months of traffic recovery."),
            ("Can you redesign our site without changing our CMS?", "Yes — redesigns can be executed within your existing CMS (WordPress, Shopify, Webflow, custom). This is typically faster and lower-risk than a CMS migration, as the underlying data structure and URLs can often be preserved. If your current CMS is limiting the design or performance goals you want to achieve, Lumo will provide an honest assessment of whether a CMS migration is worth the additional cost and risk."),
            ("What happens to our SEO rankings immediately after launch?", "A small amount of ranking fluctuation in the first 2–4 weeks after redesign launch is normal — Google is re-crawling and re-evaluating the new site structure. With proper redirect implementation and technical SEO configuration, rankings should return to baseline within 4–6 weeks. If significant drops occur beyond this window, Lumo's post-launch monitoring protocol catches the cause (missed redirects, canonicalisation errors, coverage issues) and implements fixes before they compound."),
        ],
        "cta_h2": "Ready for a Redesign That Converts Better and Ranks Higher?",
        "cta_sub": "Get a free website audit — we'll assess your current conversion rates, Core Web Vitals, and SEO equity, then show you exactly what a data-informed redesign would deliver for your business.",
        "schema_service_name": "Website Redesign Services",
        "schema_service_desc": "Conversion-focused website redesigns for US businesses — SEO equity preservation, performance optimisation, and modern design that improves both rankings and revenue.",
    },

    "connected-tv-advertising": {
        "title_tag":  "Connected TV Advertising Agency | CTV & OTT Ad Management | Lumo AI",
        "meta_desc":  "Connected TV (CTV) and OTT advertising from Lumo AI Agency. Streaming TV ads on Hulu, Peacock, Tubi, and premium CTV inventory — unskippable, household-targeted, and performance-tracked. Free audit.",
        "canonical":  "https://lumoaiagency.com/services/connected-tv-advertising",
        "og_title":   "Connected TV Advertising Agency | Lumo AI Agency",
        "og_desc":    "Reach cord-cutters on Hulu, Peacock, Tubi, and premium streaming with unskippable CTV ads. Lumo manages connected TV advertising with household targeting and cross-device attribution for US brands.",
        "h1_html":    "Connected TV Ads That Reach <span class=\"hl-lime\">Cord-Cutters</span> on Every Streaming Screen",
        "badge":      "CTV & OTT Advertising Specialists",
        "lead":       "Traditional TV advertising is dying — but streaming TV is exploding. 87% of US households now have at least one connected TV device, and cord-cutting accelerates every quarter. Lumo manages Connected TV advertising on premium streaming inventory — Hulu, Peacock, Tubi, and thousands of publisher apps — with household targeting and attribution that traditional TV never offered.",
        "stat1_num": "87%",  "stat1_lbl": "Of US households have at least one connected TV device",
        "stat2_num": "2.3B", "stat2_lbl": "Hours of streaming content watched daily in the US",
        "stat3_num": "95%",  "stat3_lbl": "Completion rate for CTV ads vs. 70% for online video",
        "why_h2": "Why CTV Is the New TV Advertising for Performance-Minded Brands",
        "why_p1": "Linear TV advertising — buying spots on broadcast or cable channels — offers minimal targeting, no performance data beyond reach and frequency estimates, and no connection between ad exposure and measurable business outcomes. Connected TV advertising flips every one of these limitations. CTV ads target specific households by demographics, interests, geographic location, and purchase behaviour — not just 'viewers of this show.'",
        "why_p2": "CTV's completion rate advantage is significant. Streaming platform ads are typically unskippable (15–30 seconds), particularly on ad-supported tiers of premium platforms. When viewers can't skip, your entire message is delivered — with 95% completion rates versus 70% for pre-roll online video and far lower rates for display ads. Combined with full-screen, living-room-sized creative, CTV delivers the impact of traditional TV with the targeting of digital.",
        "why_p3": "Lumo manages CTV advertising through DSPs with access to premium streaming inventory — negotiating CPMs below what direct buys offer, applying audience segmentation that broadcast can't match, and connecting CTV exposure to website visits, store traffic, and conversions through cross-device attribution. You can measure whether someone saw your streaming ad and visited your website within 14 days — something linear TV advertising has never offered.",
        "services_h2": "Our Connected TV Advertising Services",
        "services": [
            ("📺", "CTV Campaign Management", "Premium connected TV ad placement across Hulu, Peacock, Tubi, Pluto TV, discovery+, and thousands of streaming app publisher inventory — managed programmatically through DSPs with household audience targeting."),
            ("🎯", "Household Audience Targeting", "IP-based household targeting by demographics, income, purchase behaviour, and geographic location — reaching the right households across every device in the home, from smart TVs to tablets and mobile phones."),
            ("🎬", "CTV Creative Production", "15 and 30-second unskippable ad production optimised for TV-screen viewing — high-production-value creative with clear messaging, strong brand presence, and end-card CTA for cross-device follow-up."),
            ("🔗", "Cross-Device Attribution", "Attribution connecting CTV ad exposure to web visits, app downloads, and conversions on connected devices — measuring the downstream impact of streaming TV impressions on measurable business outcomes."),
            ("🏠", "OTT & Streaming App Inventory", "Over-the-top (OTT) advertising across the full streaming ecosystem — ad-supported tiers of premium services, free streaming apps, and connected device manufacturer inventory (Roku Channel, Samsung TV Plus, Fire TV)."),
            ("📊", "CTV Reporting & Attribution", "Household reach and frequency reporting, completion rate tracking, cross-device website lift analysis, brand safety monitoring, and monthly CTV impact reports connecting streaming investment to business outcomes."),
        ],
        "process": [
            ("🎯", "Audience & Strategy", "Define target household profile, select streaming platforms and inventory types, set reach and frequency goals, and map CTV to your broader media mix — ensuring CTV complements rather than duplicates other channels."),
            ("🎬", "Creative & Setup", "CTV ad creative production in required formats (MP4, MOV, VAST-compatible), DSP campaign configuration, audience segment setup, brand safety parameters, and measurement pixel implementation."),
            ("🚀", "Launch & Monitor", "Campaign launch with daily delivery monitoring, completion rate tracking, frequency management, and cross-device attribution window configuration — ensuring correct measurement from day one."),
            ("📈", "Optimise & Report", "Monthly performance review — household reach, completion rates, CPM trends, and cross-device lift analysis — with creative refresh recommendations and audience strategy adjustments based on performance data."),
        ],
        "price_from": "$2,500",
        "price_note": "per month management fee — media spend is separate (minimum $5,000/mo recommended for CTV reach)",
        "faqs": [
            ("What's the difference between CTV and OTT advertising?", "CTV (Connected TV) refers to the device — any TV set connected to the internet (smart TVs, Roku, Apple TV, gaming consoles). OTT (Over-the-Top) refers to the delivery method — streaming content delivered over the internet rather than cable or satellite. In practice, advertisers use the terms interchangeably. CTV/OTT advertising covers all streaming TV inventory accessed through connected devices, distinguishing it from linear TV (broadcast/cable) and desktop/mobile video advertising."),
            ("Which streaming platforms can I advertise on through Lumo?", "Through DSP-based programmatic buying, Lumo can access inventory on Hulu, Peacock, Tubi, Pluto TV, discovery+, Philo, Fubo, ESPN+, Paramount+, Samsung TV Plus, Roku Channel, Amazon Fire TV, and thousands of publisher streaming apps across categories (news, sports, entertainment, lifestyle). Some premium publishers (Netflix, Disney+) don't sell advertising programmatically and require direct insertion orders at much higher minimum spends."),
            ("How does CTV targeting work?", "CTV targeting uses IP addresses to identify households, then applies audience data from third-party data providers (demographics, income, purchase behaviour) and first-party data activation (matching your customer list to connected TV households). This allows targeting by household income, geographic location, purchase category (e.g., in-market for automobiles), and behavioural data — significantly more precise than linear TV's demographic daypart targeting."),
            ("Can CTV advertising be measured for direct response, not just brand awareness?", "Yes — cross-device attribution connects CTV ad exposure to website visits, app downloads, and conversions on other devices within the same household. If someone sees your streaming ad on their TV and visits your website from their phone the next day, that conversion event can be attributed to the CTV impression. Completion rate, household reach, frequency, and cross-device lift are the standard performance metrics for CTV campaigns."),
            ("What creative specs are required for CTV advertising?", "Standard CTV ad formats: 15-second and 30-second video (MP4 or MOV), 16:9 aspect ratio (1920×1080px minimum), H.264 encoding, AAC audio. Ads must be delivered as VAST (Video Ad Serving Template) files or uploaded directly to the DSP. Unlike social video, CTV ads are viewed on large screens — production quality matters more than on mobile. Captions are recommended for accessibility and for moments when audio is low. Lumo handles creative production as part of CTV campaign setup."),
        ],
        "cta_h2": "Ready to Reach Your Audience on the Streaming Screens They Use Every Day?",
        "cta_sub": "Get a free CTV advertising strategy session — we'll assess your audience's streaming behaviour, map the right inventory and targeting approach, and show you what a CTV campaign would look like for your business.",
        "schema_service_name": "Connected TV Advertising Services",
        "schema_service_desc": "CTV and OTT advertising management for US brands — streaming TV ads on Hulu, Peacock, Tubi, and premium inventory with household targeting and cross-device attribution.",
    },

    "apple-search-ads": {
        "title_tag":  "Apple Search Ads Agency | iOS App Store Ad Management | Lumo AI",
        "meta_desc":  "Apple Search Ads management from Lumo AI Agency. iOS App Store advertising — Search Ads Advanced, keyword strategy, creative optimisation, and ROAS tracking for US app publishers. Free ASA audit.",
        "canonical":  "https://lumoaiagency.com/services/apple-search-ads",
        "og_title":   "Apple Search Ads Agency | Lumo AI Agency",
        "og_desc":    "65% of app downloads come from App Store search — and Apple Search Ads captures buyers at the exact moment they search. Lumo manages ASA campaigns for iOS app publishers with keyword and creative optimisation.",
        "h1_html":    "Apple Search Ads That <span class=\"hl-lime\">Capture App Downloads</span> at the Moment of Search",
        "badge":      "Apple Search Ads Specialists",
        "lead":       "Apple Search Ads appear at the top of App Store search results — reaching users at the highest-intent moment in the app discovery journey. With 65% of App Store downloads originating from search, ASA is the highest-converting paid channel available to iOS app publishers. Lumo manages Search Ads Advanced campaigns with keyword strategy and creative optimisation.",
        "stat1_num": "65%", "stat1_lbl": "Of app downloads start with an App Store search",
        "stat2_num": "50%", "stat2_lbl": "Of clicks on App Store search ads result in a download",
        "stat3_num": "60%", "stat3_lbl": "Of Apple Search Ads conversions come from users new to the app",
        "why_h2": "Why Apple Search Ads Are the Highest-Intent Paid Channel for iOS Apps",
        "why_p1": "Apple Search Ads are fundamentally different from social app install ads. When someone searches 'meditation app' on the App Store, they're actively looking to download something right now — that's purchase intent, not passive interest. ASA places your app at the top of these searches, capturing users who have already decided to install an app in your category and are evaluating which one to choose.",
        "why_p2": "Apple's privacy framework (App Tracking Transparency, iOS 14.5+) has significantly degraded targeting precision on Meta and Google for iOS apps. Many advertisers have seen iOS app install costs increase 30–50% on those platforms. Apple Search Ads operates within Apple's own privacy ecosystem — it doesn't require cross-app tracking consent and maintains consistent performance regardless of user privacy settings, making it a more reliable iOS acquisition channel post-ATT.",
        "why_p3": "Lumo manages Apple Search Ads Advanced (ASA Advanced) — the full-featured platform with keyword-level control, custom product pages, and advanced attribution — rather than the simplified Search Ads Basic product. We build keyword strategies from App Store search data, set up discovery campaigns to find new high-performing terms, optimise custom product page creative for different audience segments, and track install-to-event attribution for LTV-based optimisation.",
        "services_h2": "Our Apple Search Ads Services",
        "services": [
            ("🔍", "Keyword Research & Strategy", "App Store search-specific keyword research — identifying high-intent search terms in your category, competitor brand terms, and category terms — with match type strategy and bid management across exact, broad, and search match."),
            ("📱", "ASA Advanced Campaign Setup", "Campaign architecture design across the four ASA campaign types — Brand, Competitor, Category, and Discovery — with ad group segmentation, keyword assignments, and CPT bid strategy for each."),
            ("🖼️", "Creative Optimisation", "Custom Product Page creation for different audience segments and campaign types — testing screenshot sequences, feature highlight images, and preview video hooks through Apple's native A/B testing integrated with ASA."),
            ("📊", "Attribution & ROAS Tracking", "MMP (Mobile Measurement Partner) integration — Adjust, AppsFlyer, or Singular — for install-to-revenue attribution, cohort analysis, LTV tracking by keyword, and ROAS reporting connecting ASA spend to in-app revenue."),
            ("🔄", "Negative Keyword Management", "Ongoing search term report mining to identify irrelevant queries, competitor terms to exclude, and category mismatches — maintaining bid efficiency by eliminating wasted spend on non-converting search terms."),
            ("📈", "Performance Reporting & Optimisation", "Weekly install volume and CPT (cost-per-tap) monitoring, monthly TTR (tap-through rate) and CVR analysis by campaign and keyword, and ROAS reporting — with bid adjustments and keyword expansion based on performance data."),
        ],
        "process": [
            ("🔍", "Keyword & Competitor Research", "App Store keyword research, competitor campaign analysis (via third-party intelligence tools), category term mapping, and campaign architecture design — keyword strategy agreed before any spend begins."),
            ("🏗️", "Campaign Build & MMP Setup", "ASA Advanced campaign setup across all four campaign types, MMP integration for attribution, custom product page creation, and conversion event configuration — with test budget to validate tracking before full launch."),
            ("🚀", "Launch & Optimise", "Campaign launch with daily monitoring for first 14 days, search term report mining for negatives, bid adjustments based on CPT and CVR data, and keyword expansion from discovery campaign results."),
            ("📈", "Scale & Report", "Scale best-performing keywords, add new campaign types as data matures, quarterly keyword strategy updates, and monthly ROAS reporting with cohort-based LTV analysis by acquisition keyword."),
        ],
        "price_from": "$1,200",
        "price_note": "per month management fee — Apple Search Ads spend is separate (minimum $2,000/mo recommended)",
        "faqs": [
            ("What's the difference between Apple Search Ads Basic and Advanced?", "Search Ads Basic is Apple's simplified, automated product — you set a budget and Apple manages bids and targeting automatically. It's easy to start but offers limited optimisation control. Search Ads Advanced gives full keyword control, custom bids, audience refinements, A/B testing with custom product pages, and detailed performance data. Lumo only manages Search Ads Advanced — the additional complexity is where the meaningful optimisation opportunity exists."),
            ("How does Apple's privacy framework (ATT) affect Apple Search Ads?", "Apple Search Ads operates within Apple's own first-party data ecosystem and doesn't require App Tracking Transparency consent from users. This means ASA performance is not degraded by low ATT opt-in rates — a significant advantage over Meta and Google app install campaigns, which rely on third-party tracking affected by ATT. For iOS app publishers, ASA has become more relatively attractive as cross-platform attribution has become more difficult."),
            ("What is a Custom Product Page and why does it matter for ASA?", "Custom Product Pages (CPPs) are alternative App Store listing pages with different screenshots, preview videos, and promotional text — separate from your default App Store listing. ASA Advanced allows directing clicks from specific campaigns to specific CPPs. For example, a fitness app can show 'running-focused' screenshots to users who searched 'running tracker' and 'weight loss-focused' screenshots to users who searched 'calorie tracker' — improving relevance and install conversion rate."),
            ("How do you measure ROAS for Apple Search Ads?", "Apple Search Ads provides install and tap-through data natively. For revenue attribution — connecting installs to in-app purchases, subscriptions, or other events — we integrate a Mobile Measurement Partner (MMP) like AppsFlyer, Adjust, or Singular. The MMP tracks the full funnel from keyword click to install to first in-app event to revenue, enabling ROAS calculation at the keyword level and cohort-based LTV analysis by acquisition source."),
            ("Can Apple Search Ads work for subscription apps?", "Apple Search Ads is particularly effective for subscription apps because the high-intent audience coming from App Store search has better subscription conversion rates than users from social app install campaigns. Lumo optimises ASA for subscription apps by tracking free-trial starts, subscription initiations, and renewal events — and optimising keyword bids based on LTV (lifetime value) rather than just install volume, which better reflects the economics of subscription-based monetisation."),
        ],
        "cta_h2": "Ready to Capture App Downloads at the Highest-Intent Moment in the App Store?",
        "cta_sub": "Get a free Apple Search Ads audit — we'll review your current keyword coverage, campaign architecture, and attribution setup, then show you the install volume you're leaving on the table.",
        "schema_service_name": "Apple Search Ads Management",
        "schema_service_desc": "Apple Search Ads Advanced management for iOS app publishers — keyword strategy, campaign architecture, custom product pages, and install-to-revenue attribution.",
    },

}


# ── HTML Template ────────────────────────────────────────────────────────────
def build_page(slug, d):
    services_html = "\n".join(
        f"""          <div class="svc-card">
            <div class="svc-icon">{icon}</div>
            <h3>{title}</h3>
            <p>{desc}</p>
          </div>"""
        for icon, title, desc in d["services"]
    )

    process_html = "\n".join(
        f"""          <div class="step-card">
            <div class="step-num">{i+1:02d}</div>
            <div class="step-icon">{icon}</div>
            <h3>{title}</h3>
            <p>{desc}</p>
          </div>"""
        for i, (icon, title, desc) in enumerate(d["process"])
    )

    faq_html = "\n".join(
        f"""        <div class="faq-item">
          <button class="faq-q" aria-expanded="false">{q}<span class="faq-chevron">›</span></button>
          <div class="faq-a"><p>{a}</p></div>
        </div>"""
        for q, a in d["faqs"]
    )

    schema = {
        "@context": "https://schema.org",
        "@graph": [
            {
                "@type": "WebPage",
                "@id": d["canonical"],
                "url": d["canonical"],
                "name": d["title_tag"],
                "description": d["meta_desc"],
                "breadcrumb": {
                    "@type": "BreadcrumbList",
                    "itemListElement": [
                        {"@type": "ListItem", "position": 1, "name": "Home", "item": "https://lumoaiagency.com/"},
                        {"@type": "ListItem", "position": 2, "name": "Services", "item": "https://lumoaiagency.com/services"},
                        {"@type": "ListItem", "position": 3, "name": d["schema_service_name"], "item": d["canonical"]},
                    ]
                }
            },
            {
                "@type": "Service",
                "name": d["schema_service_name"],
                "description": d["schema_service_desc"],
                "provider": {
                    "@type": "Organization",
                    "name": "Lumo AI Agency",
                    "url": "https://lumoaiagency.com"
                },
                "areaServed": {"@type": "Country", "name": "United States"},
                "serviceType": d["schema_service_name"],
            },
            {
                "@type": "FAQPage",
                "mainEntity": [
                    {"@type": "Question", "name": q, "acceptedAnswer": {"@type": "Answer", "text": a}}
                    for q, a in d["faqs"]
                ]
            }
        ]
    }

    return f"""<!DOCTYPE html>
<html lang="en-US">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>{d["title_tag"]}</title>
  <meta name="description" content="{d["meta_desc"]}">
  <link rel="canonical" href="{d["canonical"]}">
  <meta property="og:type" content="website">
  <meta property="og:title" content="{d["og_title"]}">
  <meta property="og:description" content="{d["og_desc"]}">
  <meta property="og:url" content="{d["canonical"]}">
  <meta name="twitter:card" content="summary_large_image">
  <script type="application/ld+json">{json.dumps(schema, indent=2)}</script>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link href="https://fonts.googleapis.com/css2?family=Berkshire+Swash&family=Syne:wght@600;700;800&family=Inter:wght@400;500;600&display=swap" rel="stylesheet">
  <style>
    :root{{--bg:#0D0D14;--surface:#13131f;--primary:#B3FF00;--secondary:#7C3AED;--accent:#00F5FF;--text:#E8E8F0;--muted:#8888A8;--border:rgba(255,255,255,.08)}}
    *,*::before,*::after{{box-sizing:border-box;margin:0;padding:0}}
    html{{scroll-behavior:smooth}}
    body{{background:var(--bg);color:var(--text);font-family:'Inter',sans-serif;line-height:1.6;overflow-x:hidden}}
    a{{color:inherit;text-decoration:none}}
    img{{max-width:100%}}
    nav{{position:sticky;top:0;z-index:900;background:rgba(13,13,20,.92);backdrop-filter:blur(12px);border-bottom:1px solid var(--border)}}
    .nav-inner{{max-width:1180px;margin:0 auto;padding:0 24px;height:68px;display:flex;align-items:center;justify-content:space-between}}
    .nav-logo{{font-family:'Berkshire Swash',serif;font-size:1.45rem;background:linear-gradient(135deg,var(--primary),var(--accent));-webkit-background-clip:text;-webkit-text-fill-color:transparent;background-clip:text}}
    .nav-links{{display:flex;gap:32px;list-style:none}}
    .nav-links a{{font-size:.9rem;font-weight:500;color:var(--muted);transition:color .2s}}
    .nav-links a:hover,.nav-links a.active{{color:#fff}}
    .nav-cta .btn-lime{{background:var(--primary);color:#000;font-weight:700;font-size:.85rem;padding:10px 22px;border-radius:8px;transition:opacity .2s}}
    .nav-cta .btn-lime:hover{{opacity:.85}}
    .hero{{padding:100px 24px 80px;text-align:center;background:radial-gradient(ellipse 80% 50% at 50% 0%,rgba(124,58,237,.18) 0%,transparent 70%)}}
    .hero-inner{{max-width:800px;margin:0 auto}}
    .breadcrumb{{font-size:.8rem;color:var(--muted);margin-bottom:24px}}
    .breadcrumb a{{color:var(--muted)}} .breadcrumb a:hover{{color:#fff}}
    .badge{{display:inline-block;background:rgba(179,255,0,.12);color:var(--primary);border:1px solid rgba(179,255,0,.3);padding:6px 16px;border-radius:999px;font-size:.8rem;font-weight:600;margin-bottom:24px;letter-spacing:.04em;text-transform:uppercase}}
    h1{{font-family:'Syne',sans-serif;font-size:clamp(2rem,5vw,3.2rem);font-weight:800;line-height:1.15;margin-bottom:24px}}
    .hl-lime{{color:var(--primary)}}
    .lead{{font-size:1.1rem;color:var(--muted);max-width:640px;margin:0 auto 40px}}
    .hero-ctas{{display:flex;gap:16px;justify-content:center;flex-wrap:wrap}}
    .btn-primary{{background:var(--primary);color:#000;font-weight:700;padding:14px 32px;border-radius:10px;font-size:1rem;transition:opacity .2s}}
    .btn-primary:hover{{opacity:.85}}
    .btn-outline{{border:1px solid var(--border);color:var(--text);padding:14px 32px;border-radius:10px;font-size:1rem;transition:border-color .2s}}
    .btn-outline:hover{{border-color:var(--primary)}}
    .stats{{background:var(--surface);border-top:1px solid var(--border);border-bottom:1px solid var(--border);padding:48px 24px}}
    .stats-inner{{max-width:900px;margin:0 auto;display:grid;grid-template-columns:repeat(3,1fr);gap:32px;text-align:center}}
    .stat-num{{font-family:'Syne',sans-serif;font-size:2.4rem;font-weight:800;color:var(--primary)}}
    .stat-lbl{{font-size:.85rem;color:var(--muted);margin-top:6px}}
    .why{{padding:96px 24px}}
    .why-inner{{max-width:1100px;margin:0 auto;display:grid;grid-template-columns:1fr 1fr;gap:64px;align-items:start}}
    .section-label{{font-size:.75rem;font-weight:700;color:var(--primary);letter-spacing:.1em;text-transform:uppercase;margin-bottom:12px}}
    .section-title{{font-family:'Syne',sans-serif;font-size:clamp(1.6rem,3vw,2.2rem);font-weight:800;line-height:1.2;margin-bottom:24px}}
    .why-text p{{color:var(--muted);margin-bottom:16px;line-height:1.75}}
    .why-card{{background:var(--surface);border:1px solid var(--border);border-radius:16px;padding:32px}}
    .why-card h3{{font-family:'Syne',sans-serif;font-size:1rem;font-weight:700;margin-bottom:16px;color:var(--primary)}}
    .why-card ul{{list-style:none;display:flex;flex-direction:column;gap:10px}}
    .why-card li{{font-size:.9rem;color:var(--muted);padding-left:20px;position:relative}}
    .why-card li::before{{content:'✓';position:absolute;left:0;color:var(--primary);font-weight:700}}
    .services{{padding:96px 24px;background:var(--surface)}}
    .services-inner{{max-width:1100px;margin:0 auto}}
    .section-header{{text-align:center;margin-bottom:56px}}
    .svc-grid{{display:grid;grid-template-columns:repeat(3,1fr);gap:24px}}
    .svc-card{{background:var(--bg);border:1px solid var(--border);border-radius:16px;padding:28px;transition:border-color .2s}}
    .svc-card:hover{{border-color:var(--primary)}}
    .svc-icon{{font-size:2rem;margin-bottom:16px}}
    .svc-card h3{{font-family:'Syne',sans-serif;font-size:1rem;font-weight:700;margin-bottom:10px}}
    .svc-card p{{font-size:.88rem;color:var(--muted);line-height:1.65}}
    .process{{padding:96px 24px}}
    .process-inner{{max-width:1100px;margin:0 auto}}
    .step-grid{{display:grid;grid-template-columns:repeat(4,1fr);gap:24px;margin-top:56px}}
    .step-card{{background:var(--surface);border:1px solid var(--border);border-radius:16px;padding:28px}}
    .step-num{{font-family:'Syne',sans-serif;font-size:2rem;font-weight:800;color:var(--primary);opacity:.4;line-height:1}}
    .step-icon{{font-size:1.6rem;margin:12px 0}}
    .step-card h3{{font-family:'Syne',sans-serif;font-size:.95rem;font-weight:700;margin-bottom:8px}}
    .step-card p{{font-size:.85rem;color:var(--muted);line-height:1.65}}
    .pricing{{padding:96px 24px;background:var(--surface)}}
    .pricing-inner{{max-width:520px;margin:0 auto;text-align:center}}
    .pricing-box{{background:var(--bg);border:1px solid var(--border);border-radius:20px;padding:48px 40px;margin-top:40px}}
    .price-from{{font-size:.85rem;color:var(--muted);margin-bottom:8px}}
    .price-val{{font-family:'Syne',sans-serif;font-size:3rem;font-weight:800;color:var(--primary)}}
    .price-note{{font-size:.85rem;color:var(--muted);margin-top:8px;margin-bottom:32px}}
    .faq{{padding:96px 24px}}
    .faq-inner{{max-width:760px;margin:0 auto}}
    .faq-list{{margin-top:48px;display:flex;flex-direction:column;gap:12px}}
    .faq-item{{background:var(--surface);border:1px solid var(--border);border-radius:12px;overflow:hidden}}
    .faq-q{{width:100%;background:none;border:none;color:var(--text);font-family:'Inter',sans-serif;font-size:.95rem;font-weight:600;padding:20px 24px;text-align:left;cursor:pointer;display:flex;justify-content:space-between;align-items:center;gap:16px}}
    .faq-chevron{{font-size:1.4rem;color:var(--primary);transition:transform .3s;flex-shrink:0}}
    .faq-q[aria-expanded="true"] .faq-chevron{{transform:rotate(90deg)}}
    .faq-a{{max-height:0;overflow:hidden;transition:max-height .35s ease}}
    .faq-a p{{padding:0 24px 20px;color:var(--muted);font-size:.9rem;line-height:1.7}}
    .cta-band{{padding:96px 24px;background:radial-gradient(ellipse 70% 60% at 50% 50%,rgba(124,58,237,.25) 0%,transparent 70%);text-align:center}}
    .cta-band h2{{font-family:'Syne',sans-serif;font-size:clamp(1.6rem,3vw,2.4rem);font-weight:800;margin-bottom:16px}}
    .cta-band p{{color:var(--muted);max-width:560px;margin:0 auto 40px}}
    footer{{background:var(--surface);border-top:1px solid var(--border);padding:64px 24px 32px}}
    .footer-inner{{max-width:1180px;margin:0 auto}}
    .footer-top{{display:grid;grid-template-columns:1.4fr 1fr 1fr 1fr;gap:48px;margin-bottom:48px}}
    .footer-brand p{{color:var(--muted);font-size:.88rem;margin-top:12px;line-height:1.6;max-width:260px}}
    .footer-col h4{{font-size:.78rem;font-weight:700;color:var(--muted);letter-spacing:.08em;text-transform:uppercase;margin-bottom:16px}}
    .footer-col ul{{list-style:none;display:flex;flex-direction:column;gap:10px}}
    .footer-col li a{{font-size:.88rem;color:var(--muted);transition:color .2s}}
    .footer-col li a:hover{{color:#fff}}
    .footer-bottom{{border-top:1px solid var(--border);padding-top:24px;display:flex;justify-content:space-between;align-items:center;flex-wrap:wrap;gap:12px}}
    .footer-bottom p{{font-size:.8rem;color:var(--muted)}}
    .footer-bottom-links{{display:flex;gap:24px}}
    .footer-bottom-links a{{font-size:.8rem;color:var(--muted);transition:color .2s}}
    .footer-bottom-links a:hover{{color:#fff}}
    .social-links{{display:flex;gap:12px;margin-top:16px}}
    .social-links a{{width:34px;height:34px;border:1px solid var(--border);border-radius:8px;display:flex;align-items:center;justify-content:center;transition:border-color .2s;flex-shrink:0}}
    .social-links a:hover{{border-color:var(--primary)}}
    .social-links svg{{width:16px;height:16px;fill:var(--muted)}}
    @media(max-width:900px){{.why-inner{{grid-template-columns:1fr}}.svc-grid{{grid-template-columns:repeat(2,1fr)}}.step-grid{{grid-template-columns:repeat(2,1fr)}}.footer-top{{grid-template-columns:1fr 1fr}}}}
    @media(max-width:600px){{.stats-inner{{grid-template-columns:1fr}}.svc-grid{{grid-template-columns:1fr}}.step-grid{{grid-template-columns:1fr}}.nav-links{{display:none}}.footer-top{{grid-template-columns:1fr}}}}
  </style>
</head>
<body>

<nav>
  <div class="nav-inner">
    <a href="../index.html" class="nav-logo">Lumo AI</a>
    <ul class="nav-links">
      <li><a href="../index.html">Home</a></li>
      <li><a href="../services.html" class="active">Services</a></li>
      <li><a href="../industries/seo-for-lawyers/index.html">Industries</a></li>
      <li><a href="../about.html">About</a></li>
      <li><a href="../pricing.html">Pricing</a></li>
    </ul>
    <div class="nav-cta"><a href="../contact.html" class="btn-lime">Get Started</a></div>
  </div>
</nav>

<section class="hero">
  <div class="hero-inner">
    <nav class="breadcrumb" aria-label="Breadcrumb">
      <a href="../index.html">Home</a> › <a href="../services.html">Services</a> › {d["schema_service_name"]}
    </nav>
    <div class="badge">{d["badge"]}</div>
    <h1>{d["h1_html"]}</h1>
    <p class="lead">{d["lead"]}</p>
    <div class="hero-ctas">
      <a href="../contact.html" class="btn-primary">Get a Free Strategy Call</a>
      <a href="../services.html" class="btn-outline">View All Services</a>
    </div>
  </div>
</section>

<section class="stats">
  <div class="stats-inner">
    <div><div class="stat-num">{d["stat1_num"]}</div><div class="stat-lbl">{d["stat1_lbl"]}</div></div>
    <div><div class="stat-num">{d["stat2_num"]}</div><div class="stat-lbl">{d["stat2_lbl"]}</div></div>
    <div><div class="stat-num">{d["stat3_num"]}</div><div class="stat-lbl">{d["stat3_lbl"]}</div></div>
  </div>
</section>

<section class="why">
  <div class="why-inner">
    <div class="why-text">
      <div class="section-label">Why It Matters</div>
      <h2 class="section-title">{d["why_h2"]}</h2>
      <p>{d["why_p1"]}</p>
      <p>{d["why_p2"]}</p>
      <p>{d["why_p3"]}</p>
    </div>
    <div class="why-card">
      <h3>What You Get With Lumo</h3>
      <ul>
        <li>Dedicated specialist team — not a generalist account manager</li>
        <li>Full strategy, execution, and reporting included</li>
        <li>AI-powered insights on every engagement</li>
        <li>Transparent monthly performance reports</li>
        <li>GEO optimisation built into every strategy</li>
        <li>No lock-in contracts — performance keeps you here</li>
      </ul>
    </div>
  </div>
</section>

<section class="services">
  <div class="services-inner">
    <div class="section-header">
      <div class="section-label">What We Do</div>
      <h2 class="section-title">{d["services_h2"]}</h2>
    </div>
    <div class="svc-grid">
{services_html}
    </div>
  </div>
</section>

<section class="process">
  <div class="process-inner">
    <div class="section-header">
      <div class="section-label">How It Works</div>
      <h2 class="section-title">Our Proven 4-Step Process</h2>
    </div>
    <div class="step-grid">
{process_html}
    </div>
  </div>
</section>

<section class="pricing">
  <div class="pricing-inner">
    <div class="section-label" style="text-align:center">Investment</div>
    <h2 class="section-title" style="text-align:center">Simple, Transparent Pricing</h2>
    <div class="pricing-box">
      <div class="price-from">Starting from</div>
      <div class="price-val">{d["price_from"]}</div>
      <div class="price-note">{d["price_note"]}</div>
      <a href="../contact.html" class="btn-primary">Get a Custom Quote</a>
    </div>
  </div>
</section>

<section class="faq">
  <div class="faq-inner">
    <div class="section-label" style="text-align:center">FAQ</div>
    <h2 class="section-title" style="text-align:center">Frequently Asked Questions</h2>
    <div class="faq-list">
{faq_html}
    </div>
  </div>
</section>

<section class="cta-band">
  <h2>{d["cta_h2"]}</h2>
  <p>{d["cta_sub"]}</p>
  <a href="../contact.html" class="btn-primary">Book a Free Strategy Call</a>
</section>

<footer>
  <div class="footer-inner">
    <div class="footer-top">
      <div class="footer-brand">
        <a href="../index.html" class="nav-logo" style="font-family:'Berkshire Swash',serif;font-size:1.3rem;background:linear-gradient(135deg,#B3FF00,#00F5FF);-webkit-background-clip:text;-webkit-text-fill-color:transparent;background-clip:text">Lumo AI</a>
        <p>AI-powered marketing agency based in Austin, TX. We help US businesses grow with SEO, paid media, AI automation, and content marketing.</p>
        <div class="social-links">
          <a href="https://www.linkedin.com/company/lumo-ai-agency" aria-label="LinkedIn"><svg viewBox="0 0 24 24"><path d="M20.447 20.452h-3.554v-5.569c0-1.328-.027-3.037-1.852-3.037-1.853 0-2.136 1.445-2.136 2.939v5.667H9.351V9h3.414v1.561h.046c.477-.9 1.637-1.85 3.37-1.85 3.601 0 4.267 2.37 4.267 5.455v6.286zM5.337 7.433a2.062 2.062 0 01-2.063-2.065 2.064 2.064 0 112.063 2.065zm1.782 13.019H3.555V9h3.564v11.452zM22.225 0H1.771C.792 0 0 .774 0 1.729v20.542C0 23.227.792 24 1.771 24h20.451C23.2 24 24 23.227 24 22.271V1.729C24 .774 23.2 0 22.222 0h.003z"/></svg></a>
          <a href="https://twitter.com/lumoaiagency" aria-label="Twitter/X"><svg viewBox="0 0 24 24"><path d="M18.244 2.25h3.308l-7.227 8.26 8.502 11.24H16.17l-4.714-6.231-5.401 6.231H2.744l7.737-8.835L1.254 2.25H8.08l4.713 6.231zm-1.161 17.52h1.833L7.084 4.126H5.117z"/></svg></a>
          <a href="https://www.facebook.com/lumoaiagency" aria-label="Facebook"><svg viewBox="0 0 24 24"><path d="M24 12.073c0-6.627-5.373-12-12-12s-12 5.373-12 12c0 5.99 4.388 10.954 10.125 11.854v-8.385H7.078v-3.47h3.047V9.43c0-3.007 1.792-4.669 4.533-4.669 1.312 0 2.686.235 2.686.235v2.953H15.83c-1.491 0-1.956.925-1.956 1.874v2.25h3.328l-.532 3.47h-2.796v8.385C19.612 23.027 24 18.062 24 12.073z"/></svg></a>
        </div>
      </div>
      <div class="footer-col">
        <h4>Services</h4>
        <ul>
          <li><a href="../services/seo.html">SEO</a></li>
          <li><a href="../services/geo.html">GEO</a></li>
          <li><a href="../services/google-ads.html">Google Ads</a></li>
          <li><a href="../services/google-shopping.html">Google Shopping</a></li>
          <li><a href="../services/performance-max.html">Performance Max</a></li>
          <li><a href="../services/meta-ads.html">Meta Ads</a></li>
          <li><a href="../services/lead-generation.html">Lead Generation</a></li>
          <li><a href="../services/google-business-profile.html">GBP Management</a></li>
          <li><a href="../services/connected-tv-advertising.html">CTV Advertising</a></li>
          <li><a href="../services/website-redesign.html">Website Redesign</a></li>
          <li><a href="../services.html">All Services →</a></li>
        </ul>
      </div>
      <div class="footer-col">
        <h4>Industries</h4>
        <ul>
          <li><a href="../industries/seo-for-lawyers/index.html">Legal</a></li>
          <li><a href="../industries/seo-for-dentists/index.html">Dental</a></li>
          <li><a href="../industries/healthcare-seo/index.html">Healthcare</a></li>
          <li><a href="../industries/saas-marketing/index.html">SaaS</a></li>
          <li><a href="../industries/ecommerce-marketing/index.html">E-commerce</a></li>
          <li><a href="../industries/home-services-seo/index.html">Home Services</a></li>
          <li><a href="../industries/financial-services-marketing/index.html">Finance</a></li>
          <li><a href="../industries/restaurant-marketing/index.html">Restaurant</a></li>
          <li><a href="../industries/fitness-gym-marketing/index.html">Fitness</a></li>
          <li><a href="../industries/construction-marketing/index.html">Construction</a></li>
        </ul>
      </div>
      <div class="footer-col">
        <h4>Compare</h4>
        <ul>
          <li><a href="../compare/lumo-vs-webfx/index.html">Lumo vs WebFX</a></li>
          <li><a href="../compare/lumo-vs-thrive-agency/index.html">Lumo vs Thrive</a></li>
          <li><a href="../compare/lumo-vs-np-digital/index.html">Lumo vs NP Digital</a></li>
          <li><a href="../compare/lumo-vs-ignite-digital/index.html">Lumo vs Ignite</a></li>
          <li><a href="../compare/lumo-vs-disruptive-advertising/index.html">Lumo vs Disruptive</a></li>
          <li><a href="../compare/lumo-vs-smartsites/index.html">Lumo vs SmartSites</a></li>
        </ul>
        <h4 style="margin-top:24px">Company</h4>
        <ul>
          <li><a href="../about.html">About</a></li>
          <li><a href="../pricing.html">Pricing</a></li>
          <li><a href="../contact.html">Contact</a></li>
        </ul>
      </div>
    </div>
    <div class="footer-bottom">
      <p>© 2026 Lumo AI Agency LLC. All rights reserved.</p>
      <div class="footer-bottom-links">
        <a href="../privacy-policy.html">Privacy Policy</a>
        <a href="../terms-of-service.html">Terms of Service</a>
        <a href="../cookie-policy.html">Cookie Policy</a>
      </div>
    </div>
  </div>
</footer>

<script>
  document.querySelectorAll('.faq-q').forEach(btn => {{
    btn.addEventListener('click', () => {{
      const expanded = btn.getAttribute('aria-expanded') === 'true';
      document.querySelectorAll('.faq-q').forEach(b => {{
        b.setAttribute('aria-expanded','false');
        b.nextElementSibling.style.maxHeight = null;
      }});
      if (!expanded) {{
        btn.setAttribute('aria-expanded','true');
        btn.nextElementSibling.style.maxHeight = btn.nextElementSibling.scrollHeight + 'px';
      }}
    }});
  }});
</script>
</body>
</html>"""


def main():
    for slug, data in SERVICES.items():
        html = build_page(slug, data)
        path = os.path.join(BASE, f"{slug}.html")
        with open(path, "w", encoding="utf-8") as f:
            f.write(html)
        print(f"Created: services/{slug}.html ({len(html):,} chars)")
    print(f"\nDone. {len(SERVICES)} pages created.")

if __name__ == "__main__":
    main()
